//Just small hack.
//romi.hardiyanto et googlemail
var TabzillaIdContent =
    '<div id="tabzilla-contents">'
    + '  <div id="tabzilla-promo">'
    + '    <div class="snippet">'
    + '      <h4>Selamat Datang!</h4>'
    + '      <p>Di mana saja Anda menemukan Situs Mozilla, '
    + '         tautan berikut akan membantu Anda memulai.<br/>'
    + '         Selamat Menjelajah!</p>'
    + '    </div>'
    + '  </div>'
    + '  <div id="tabzilla-nav">'
    + '    <ul>'
    + '      <li><h2>Mozilla</h2>'
    + '        <ul>'
    + '          <li><a href="http://www.mozilla.org/about/mission.html">Misi</a></li>'
    + '          <li><a href="http://www.mozilla.org/about/">Tentang</a></li>'
    + '          <li><a href="http://www.mozilla.org/projects/">Proyek</a></li>'
    + '          <li><a href="http://support.mozilla.org/">Bantuan</a></li>'
    + '          <li><a href="https://developer.mozilla.org">Jaringan Pengembang</a></li>'
    + '        </ul>'
    + '      </li>'
    + '      <li><h2>Produk</h2>'
    + '        <ul>'
    + '          <li><a href="http://www.mozilla.org/firefox">Firefox</a></li>'
    + '          <li><a href="http://www.mozilla.org/thunderbird">Thunderbird</a></li>'
    + '        </ul>'
    + '      </li>'
    + '      <li><h2>Inovasi</h2>'
    + '        <ul>'
    + '          <li><a href="https://webfwd.org/">WebFWD</a></li>'
    + '          <li><a href="http://mozillalabs.com/">Labs</a></li>'
    + '        </ul>'
    + '      </li>'
    + '      <li><h2>Ikut Berperan</h2>'
    + '        <ul>'
    + '          <li><a href="http://www.mozilla.org/contribute/">Sukarelawan</a></li>'
    + '          <li><a href="http://www.mozilla.org/en-US/about/careers.html">Karier</a></li>'
    + '          <li><a href="http://www.mozilla.org/en-US/about/mozilla-spaces/">Temukan Kami</a></li>'
    + '          <li><a href="https://donate.mozilla.org/">Menyumbang</a></li>'
    + '          <li><a href="http://www.mozilla.org/contribute/">Selengkapnya</a></li>'
    + '        </ul>'
    + '      </li>'
    + '      <li id="tabzilla-search">'
    + '        <a href="http://www.mozilla.org/community/directory.html">Direktori Situs Web</a>'
    + '        <form title="Telusuri Berbagai Situs Mozilla" action="http://www.google.com/cse">'
    + '          <input type="hidden" value="002443141534113389537:ysdmevkkknw" name="cx">'
    + '          <input type="hidden" value="FORID:0" name="cof">'
    + '          <input type="search" placeholder="Cari" id="q" name="q">'
    + '        </form>'
    + '      </li>'
    + '    </ul>'
    + '  </div>'
    + '</div>';
jQuery(document).ready(function() {
	jQuery('#tabzilla-panel').html(TabzillaIdContent);
});